### ISSUE TITLE
The error message displayed when trying to change the name of the contract meanwhile being open is miss-leading

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/studio#11]
### Environment/Browser
Google Chrome 67.0.3396.79

### Description
The error message displayed when trying to change the name of the contract meanwhile being open is miss-leading

### Steps to reproduce
1. Open an already created smart contract 
2. Enter the `configuration` section of the contract
3. Try to rename the contract

### Expected result
Either the tool allows you to change the name while the file is open in a tab or actually the message says something like "Error: Could not rename contract source file. Close the open contract code open tab and try again."

### Actual result
<img width="589" alt="screen shot 2018-06-19 at 21 34 00" src="https://user-images.githubusercontent.com/7814134/41620591-74d4167e-740a-11e8-8d3b-91a7c99f3453.png">

### Reproducible
100%

**Comment by Bashlund** [comment]
Fixed
