### ISSUE TITLE
Consider updating Solidity version declaration to match current available compiler

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#27]
## Description

Update dapp templates and new contract file creation to point to Studio's actual Solidity compiler version. That should help preventing confusion.

## Current behavior
All new files and examples currently read:
```
pragma solidity 0.4.17;
```

## Expected behavior
Expected declaration, as of today:
```
pragma solidity 0.4.21;
```

## Expected results
Decreasing the default version number won't do any harm.
Increasing the version past the default declaration will return an error.

**Comment by Bashlund** [comment]
Fixed
