### ISSUE TITLE
Cannot select template option when clicking on the text description

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#28]
## Environment/Browser
Any version.

## Steps to reproduce
1. Got to `New DApp` section
2. Try to select a template by clicking on the text description

## Expected result
Expected to be able to select a template by clicking anywhere on the template entry, be it the radio button or the text description

## Actual result
Template options can only be selected by clicking on the radio button. Clicks to the text description don't compute i.e. miss.

**Comment by javier-tarazaga** [comment]
This will be solved in the new flow for project creation (new UX project). Closing for now.
