### ISSUE TITLE
TypeError when clicking the "Browser" button due to undefined environments property in cleaned up session

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#36]

**Comment by Bashlund** [comment]
Is this when having imported an old project?

**Comment by Bashlund** [comment]
Ok, so when having 0 projects, got it!

**Comment by filippsen** [comment]
Results in behavior similar to #38 where the _Select a Network_ button art hints for a clickable button (down arrow indicator), but no information is available at the time, before creating a project (_dappfile_ dependency).

**Comment by filippsen** [comment]
Hiding the component would be the sensible additional change.

However, the network selector component doesn't have access to that information, as it is. The issue of the app being in a bad state has been addressed in the referenced commit (cac7f6d). Leaving it as is for the moment.
