### ISSUE TITLE
No feedback when clicking Transactions button in a cleaned up session

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#38]
## Expected result
Empty transaction log window

**Comment by filippsen** [comment]
@Bashlund 
This is when you have **no projects at all** and then you click the _Transactions_ button. 

Steps to reproduce:
1. make sure you have no projects listed in the top bar
2. click _Transactions_ button

It is a clickable button, but it doesn't do anything. I understand it is context-based and requires a project with transactions, but the lack of feedback might cause an initial confusion for those learning by experimenting with the possible actions.

**Comment by javier-tarazaga** [comment]
@filippsen @Bashlund we can simply show an empty message saying that no project has been selected. What do you think?

**Comment by filippsen** [comment]
@javier-tarazaga it will be fixed in https://github.com/SuperblocksHQ/studio/issues/80

**Comment by filippsen** [comment]
Transactions button will only appear when there is a project selected. #80, commit 673a13ea

When a project is open but no transactions have been registered yet, a message will appear in the _Transaction history_ window, according to the referenced commit (e9e4c76).
