### ISSUE TITLE
Misaligned icons presented in project editor

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#46]
![studio-alignment](https://user-images.githubusercontent.com/697226/44419381-43b07b80-a57b-11e8-9dbb-cf87dfec8bf9.jpg)

**Comment by javier-tarazaga** [comment]
@filippsen Is there anything specific you need to fix this? The issue why this appears is because Font Aweseom and the `IconImg` components under the `icons/index.js` are not equally aligned. Maybe we could fix this for all the icons using an <img> by fixing it in the `IconImg` component.

**Comment by filippsen** [comment]
@javier-tarazaga This was improved by @waheed25 in the referenced commit (b67b5a2) by modifying the _Deploy_ icon art (positioning) and setting a new `style` property to both the _Deploy_ and _Interact_ buttons.
