### ISSUE TITLE
Consider improving output text to state which network a contract is being deployed to when using an external provider

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#49]
## Motivation
Adding the currently selected network to the text would make the output self-sufficient, as done with "Browser" network where the endpoint is listed.
Stating the current network would be possible based on the network id.

## Suggestions
"Switching to external provider for Rinkeby, endpoint is now unknown."
"Rinkeby: switching to external provider, endpoint is now unknown."
"Switching to external provider, endpoint is now unknown (Rinkeby)."

The warning about the endpoint is understandable, but adding the network would make it clearer. Alternatively, could be added as a new message.

**Comment by javier-tarazaga** [comment]
@filippsen could you provide some more info on this issue?

**Comment by filippsen** [comment]
@javier-tarazaga with the previous comment in mind, I'm closing the issue. Please reopen if any other questions arise.
