### ISSUE TITLE
Misaligned icons presented in file explorer

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#50]
![studio-alignment-menu](https://user-images.githubusercontent.com/697226/44419757-55dee980-a57c-11e8-9476-ed74dac8971d.jpg)

**Comment by javier-tarazaga** [comment]
@filippsen is it an issue with the icons? Can you solve it programmatically?

**Comment by filippsen** [comment]
@javier-tarazaga I changed `icon-html.svg` base `x` position directly, instead of applying a modifier to `IconHtml`, to prevent dealing with browser specific code and also because it is currently only used in a single place (`projecteditor`). 

The icons in `app` should look normalized now. Referenced commit: 854d18d

![studio-issue-html-icon](https://user-images.githubusercontent.com/697226/44906886-7ba38580-ad16-11e8-8659-067b15eace4e.jpg)
