### ISSUE TITLE
Error when reading balance from custom account loaded from seed

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#57]
## Steps to reproduce
Unlock a custom account using the provided seed in the console: "Known development Ethereum wallet seed is: ..."

## Actual result
```
Balance: <could not get balance> wei (0 Ether)
```

**Comment by Bashlund** [comment]
You chose the Custom network? Did you have a node running on localhost ?

**Comment by filippsen** [comment]
@Bashlund No, this was not when running a node on localhost. This is without selecting _Custom_ network e.g. when in Browser network.

Steps to reproduce are:
1. **Create New** "Hello World" template
2. **Edit** _Default_ account in "Select an Account" dropdown
3. **Click** _custom_
4. **Click** the _Unlock_ button
5. **Paste** the valid seed created by _Studio_ when initializing (see the _developer console_ : `butter ...`)

The **output** will be: 
> Balance: <could not get balance> wei (0 Ether)

along with an **error** in the output console.

**Comment by Bashlund** [comment]
Ok, when choosing Custom when editing/viewing an account that is unlocking the wallet for the Custom network, which always (for now) goes to localhost:8545. So it is actually trying to fetch the balance from localhost, and failing.
