### ISSUE TITLE
Error when trying to interact with contract marked as already deployed on a resumed browser session

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#67]
## Expected result
If the contract is marked as already deployed, I would expect it to work. This behavior hints for a dirty state during session resume: an already existing project is loaded and it contains data from a previous deployment phase. Still, it can't seem to access it for interacting with the contract.

## Actual result
Error when trying to interact, as if the project was not deployed.

> "Arguments parsed successfully: Hello Wodl!
> Contract freshly compiled, not recompiling.
> Switching to external provider, endpoint is now unknown.
> Contract on chain is same, not redeploying. 
> Done."

**Comment by Bashlund** [comment]
@filippsen I can't reproduce this. Trying on Browser, Custom and Rinkeby network.
I did fix a bug in web3provider.js, but I think it's unrelated.

**Comment by filippsen** [comment]
After having deployed a contract to _Rinkeby_, resuming a browser session, with a page reload or re-open, setting the network to _Rinkeby_ again and opening the _Interact_ window does enable interacting with the previously deployed contract.

The _Deploy_ output message indeed matches the description, as expected, but the interaction does work.

As with #68, retried multiple times using the same browser and _MetaMask_ (version 4.8.0), the same used for reporting the issue. Unable to reproduce it with the latest codebase, starting from a new deployment.

The sensible explanation is that it was due to the breaking issue in the provider, fixed recently by #78. Before that, the local state had a cached deployment (the dirty state mentioned in the issue description), in which I could access previously deployed contracts, but couldn't redeploy and probably had faulty behavior, including interaction, due to the same bug.
