### ISSUE TITLE
Error when trying to deploy with locked MetaMask account: unlocking it doesn't resolve without a complete page reload

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#68]
## Actual result
After unlocking _MetaMask_ and clicking the _Deploy_ button, the "no external provider found" message changes to:  
```
Arguments parsed successfully: Hello Wodl!
Contract freshly compiled, not recompiling.
Switching to external provider, endpoint is now unknown.
External account not found. Metamask unlocked?
```

**Comment by Bashlund** [comment]
I can't reproduce this.
I unsuccessfully deploy with metamask unlocked, then unlock it and press the lightning and it works.
Possibly it works because I am using the latest Metamask version: 4.9.3.

**Comment by filippsen** [comment]
Retried this several times using the same browser and MetaMask (version 4.8.0), which is the same setup that was used for reporting this bug. I couldn't reproduce it either!

Experimented with various combinations: restarting the browser, resuming existing project, resetting project, changing wallet, changing networks, touching contracts and locking and unlocking multiple times.
