### ISSUE TITLE
Vague and different error message when trying to send an interact transaction when the external provider wallet is locked

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#71]
## Actual result
When the external provider wallet is locked while the interact window is open, the error message detects that MetaMask is probably locked.
However, when closing the interact window and opening it again, the error message changes to an alert box instead:
"There is no account available to do the transaction"

**Comment by Bashlund** [comment]
I improved the error message for this in commit 54c8e38533555ed6484

**Comment by javier-tarazaga** [comment]
@Bashlund @filippsen should we consider this issue as solved and put it under review approved?

**Comment by filippsen** [comment]
Yes, the improved error message is more clear now. Thank you!
