### ISSUE TITLE
Opening MetaMask for the first time and unlocking the account after having Studio loaded doesn't automatically unlock the accounts

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#76]
## Actual result
The accounts are not unlocked until the page is reloaded.

**Comment by Bashlund** [comment]
This happens for contract interaction, when the interaction is first loaded, then metamask is opened.
It can be "fixed" by refreshing the interaction by pressing the lightning button.

Same procedure for App preview, it works when refreshing using the lightning button.

A fix could be to detect when Metamask is unlocked and automatically reload the preview and interact windows.
