### ISSUE TITLE
ReferenceError freezes the application after trying to deploy to any external network with MetaMask

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#78]
## Actual result
When deploying to _Rinkeby_, after confirming the transaction details in _MetaMask_, the following error freezes the application:

> ReferenceError: style is not defined (bundle.js line 2602 > eval:87:19)
> TypeError: this.props.dappfile is undefined (bundle.js line 2755 > eval:54:17)
> 

The _Warning_ message doesn't get solved after _MetaMask_ window is closed, probably due to the error, which prevents code from continuing processing.
After the contract has been deployed, the window is "soft refreshed" (refreshed by the application, not the browser) into a state similar to when the project is unloaded (no _Files_ hierarchy or editor open, just the project name at the top).
Does not happen when the network is set to _Browser_.

**Comment by Bashlund** [comment]
Fixed by f9624c84df269141827a40

**Comment by javier-tarazaga** [comment]
@filippsen could you please confirm this issue is being fixed and move the card to the 'Reviewed approved' if everything is fine? Thanks!

**Comment by filippsen** [comment]
@javier-tarazaga @Bashlund At the time of original writing I was unable to expand the bundle and associate the eval output with the source code. This was a simple yet crucial fix. Thanks!

OK!
