### ISSUE TITLE
After a successful deployment to Browser network, with the Show Preview window open, switching to any other network makes the Download DApp action download the Browser DApp

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#79]
## Steps to reproduce
1. Deploy the project to Browser network
2. open the Show Preview window
3. Keep the window open, then switch to any other network.
4. Click the Download DApp button

## Expected result
#75 

## Actual result
This makes the Download DApp action available, which in this case would download the HTML configured to Browser settings instead of the currently selected network Rinkeby.

A variant of #75.

This might be happening when deploying to other networks as well, but it is not possible to test it at the moment due to #78.

**Comment by javier-tarazaga** [comment]
@filippsen is there anything blocking to fix this issue?

**Comment by filippsen** [comment]
@javier-tarazaga None at all. This was solved in the referenced commit (db5a3e7). Thanks!
